---

- name: make sure sesam server prerequistes are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-server
    - java-1.8.0-openjdk

- name: make sure sesam server is installed
  yum:
    name: "{{ sesam_server_pkg }}"
    state: present
...
